//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic_Police_Information_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int id_car { get; set; }
        public string number_car { get; set; }
        public int id_driver { get; set; }
        public int id_model { get; set; }
        public int id_color { get; set; }
        public System.DateTime year_issue { get; set; }
        public System.DateTime date_GAI { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Models Models { get; set; }
    }
}
