//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic_Police_Information_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collections
    {
        public int id_collection { get; set; }
        public int id_violation { get; set; }
        public System.DateTime date_violation { get; set; }
        public System.TimeSpan time_violation { get; set; }
        public int id_driver { get; set; }
        public int id_area { get; set; }
        public Nullable<double> fine { get; set; }
        public Nullable<bool> payment_fine { get; set; }
        public bool waring { get; set; }
        public Nullable<int> period_dis { get; set; }
        public int id_inspector { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Inspectors Inspectors { get; set; }
        public virtual Violations Violations { get; set; }
    }
}
