//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic_Police_Information_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_GAIEntities : DbContext
    {
        static db_GAIEntities _context;

        public db_GAIEntities()
            : base("name=db_GAIEntities")
        {
        }

        public static db_GAIEntities GetContext()
        {
            if(_context == null)
            {
                _context = new db_GAIEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Collections> Collections { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Inspectors> Inspectors { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Violations> Violations { get; set; }
    }
}
